service: api-task

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
        - s3:*
        - ses:*
      Resource: "*"
  vpc:
    securityGroupIds:
      - sg-060065324d993329a
    subnetIds:
      - subnet-0572c93202ab367d3
      - subnet-08a4138e4efef3c83
  stage: hom
  region: sa-east-1
  timeout: 90
  memorySize: 1024
  package:
    excludeDevDependencies: true
    exclude:
      - .git/**
      - .docker/**
  environment:
# Adicionar variáveis de ambiente necessárias

functions:
  emails:
    handler: src/server.run
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      # - schedule: "rate(15 minutes)"
  reportEmail:
    handler: src/console/reportEmail.run
    events:
      - http:
          path: /cron-report-email
          method: ANY
          cors: true
      # - schedule: "rate(10 minutes)"
      # - schedule: "cron(0 9 ? * FRI *)"


plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-offline-scheduler
